server:
  port: 8082

spring:
  application:
    name: service-comsumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/, http://localhost:8089/eureka/    # 注册中心地址,可注册到多台服务实例中

